# Generated by Django 5.1 on 2024-08-18 10:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vacancies/')),
                ('position', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Tam ştat', 'Tam ştat'), ('Yarım ştat', 'Yarım ştat'), ('Təcrübəçi', 'Təcrübəçi')], default='Tam ştat', max_length=255)),
                ('deadline', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
