# Generated by Django 5.1 on 2024-08-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterial',
            name='image',
            field=models.ImageField(default='', upload_to='video-materials/'),
            preserve_default=False,
        ),
    ]
