# Generated by Django 5.1 on 2024-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomaterial',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
