# Generated by Django 5.1 on 2024-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinform',
            name='experience_years',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
